POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name": "Arti",
  "email": "artidfghj@gmail.com"
}

###

POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name": "Marek",
  "email": "marekszdfxgchvjbknlm@gmail.com"
}

###
POST http://localhost:8080/api/players/activate
Content-Type: application/json

{
  "secret": "3e6cab2f-5171-4528-8928-9590bd3c5e0f"
}

###
GET http://localhost:8080/api/players/activated/3e6cab2f-5171-4528-8928-9590bd3c5e0f
Accept: application/json

###
GET http://localhost:8080/api/players/all
Accept: application/json

<> 2022-03-01T145036.200.json

###

POST http://localhost:8080/api/games
Content-Type: application/json

{
  "reportedBy": {
    "secret": "dfbbf7d3-ec40-4f2a-b968-a2de7cc03275"
  },
  "ranking": [
    [
      {
        "uuid": "b72cf377-b79d-4010-93ef-85a3e396f517"
      }
    ],
    [
      {
        "uuid": "4f6e3b9d-d1cc-4c4c-8c6d-370f2b8e5571"
      }
    ]
  ]
}

###

GET http://localhost:8080/api/games?count=10
Accept: application/json

<> 2022-03-01T145036.200.json

###

POST http://localhost:8080/api/players/resend/55ca8d21-10de-4dc8-a7aa-4488a3b739b5
Content-Type: application/json

{
  "email": "test@test.test"
}

###

