POST http://localhost:8080/api/player
Content-Type: application/json

{
  "name":  "Arti",
  "email":  "arti@gmail.com"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json

{
  "name":  "Marek",
  "email":  "marek@gmail.com"
}

###
GET http://localhost:8080/api/player
Accept: application/json

<> 2022-03-01T145036.200.json

###

POST http://localhost:8080/api/game
Content-Type: application/json

{
  "reportedBySecret":  "8d8534c7-5af0-4c0c-b7bc-aa58597ea259",
  "results":  [
    ["fb2dbf33-621b-45b8-8c8d-671b830d6097"],
    ["76195472-c0f5-48a2-a4e2-1899cc5ac1fb"]
  ]
}

###

GET http://localhost:8080/api/game?count=2
Accept: application/json

<> 2022-03-01T145036.200.json

###