POST http://localhost:8080/api/player
Content-Type: application/json

{
  "name":  "Kamil",
  "email":  "kamil223@gmail.com"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json

{
  "name":  "Arti",
  "email":  "arti123i@gmail.com"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json

{
  "name":  "Marek",
  "email":  "marek111@gmail.com"
}

###
POST http://localhost:8080/api/player
Content-Type: application/json

{
  "name":  "Marian",
  "email":  "mario223@gmail.com"
}

###
GET http://localhost:8080/api/player
Accept: application/json

<> 2022-03-01T145036.200.json

###

POST http://localhost:8080/api/game
Content-Type: application/json

{
  "reportedBySecret":  "c2341fe9-a045-4b99-a913-93f82799b7ce",
  "results":  [
    ["d60911f4-bf35-4aab-82aa-d6d170073346", "6edd3c77-4488-4819-b7bd-6545207c1bde"],
    ["c728e5f1-ac64-4ffa-a6b3-1344c4989a6e"]
  ]
}

###
POST http://localhost:8080/api/game
Content-Type: application/json

{
  "reportedBySecret":  "e47f212b-7c1b-48c0-9c6b-c762ee4ce928",
  "results":  [
    ["9d74807f-72b3-4abf-bfb7-86e5f2d94a15", "a365aa3b-fa2e-49a8-b1c4-721c8ee38988"],
    ["bf840f63-266a-4f66-a9ae-3662889d4687"]
  ]
}

###

GET http://localhost:8080/api/game?count=10
Accept: application/json

<> 2022-03-01T145036.200.json

###
