POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name":  "Kamil",
  "email":  "kamil223@gmail.com"
}

###

POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name":  "Arti",
  "email":  "arti123i@gmail.com"
}

###

POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name":  "Marek",
  "email":  "marek111@gmail.com"
}

###
POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name":  "Marian",
  "email":  "mario223@gmail.com"
}

###
GET http://localhost:8080/api/players/all
Accept: application/json

<> 2022-03-01T145036.200.json

###

POST http://localhost:8080/api/games
Content-Type: application/json

{
  "reportedBySecret":  "4ae4e496-12a7-4873-b4d8-294a871cebbf",
  "results":  [
    ["0bbce9d0-10e5-4666-a83c-b5f797830ba3"],
    ["d5e8cfcc-33cf-4901-9117-eb87caf33691"]
  ]
}

###
POST http://localhost:8080/api/games
Content-Type: application/json

{
  "reportedBySecret":  "c9e5f453-b7dc-4076-a9d6-90d11759afbb",
  "results":  [
    ["d5e8cfcc-33cf-4901-9117-eb87caf33691", "ff355620-271d-43ee-9a60-f530417b0698"],
    ["69dd04d3-6062-45aa-92ee-7229c991f9ec"]
  ]
}

###

GET http://localhost:8080/api/games?count=10
Accept: application/json

<> 2022-03-01T145036.200.json

###
